== About

proto2asciidoc generates asciidoc documentation from a Protobuffer definition
file. The goal of the project was to prevent API documentation inconsistenties
between the actual API and the docs.

By generating the code from the Protobuf definition the documentation is always
in sync.

It can either generate only the Protobuffer Messages/Enums as output or full
api-docs output depending on the flags passed.

Can be used in conjunction with https://github.com/productsupcom/code2asciidoc[code2asciidoc]
to produce even more consistent API documentation.

== Variables

When using `api-docs` output, the tool will include a few variables. These can be
set through asciidoctor variables.

Example how to do it in a Makefile

.Makefile
[source,Makefile]
----
include::../Makefile[tag=variables]
----

== Extension

This tool assumes the extension in `asciidoc/extension` will be loaded when using
AsciiDoctor.

The following snippet can be used inside a Makefile.

NOTE: Of course you have to ensure that the directory is in a location your
Makefile can find it.

.Makefile
[source,Makefile]
----
include::../Makefile[tag=extension]
----

The following shows how the README (if on Github) you're currently reading 
has been produced.

.Optional formats
----
include::../Makefile[tag=markdown]
----