== Example

Please checkout the `docs/` directory for examples how to structure your docs
to use this tool.
Inside `docs/generated/api.adoc` you can find a `--api-docs` output generated by
this tool.
The file `docs/generated/message_enums_only.adoc` is the output when the previous
mentioned flag is not passed.

To generate the docs you can run the following yourself:

.Generate full api-docs
[source,shell]
----
./proto2asciidoc --source $(pwd)/examples/examples.proto \
--out docs/generated/api.adoc --overwrite --api-docs
----

If this tool is used in conjunction with https://github.com/productsupcom/code2asciidoc[code2asciidoc]
you will most probably have sample adoc's you want to include. This can be done
as following.
If there are multiple, simply comma separate them.

.Generate full api-docs with API samples from code2asciidoc
[source,shell]
----
./proto2asciidoc --source $(pwd)/examples/examples.proto \
--out docs/generated/api.adoc --overwrite --api-docs \
--sample-files $(pwd)/docs/generated/api/someservice/response_samples.adoc
----

The following is useful for imported Protobuf declaration (e.g. from Google).
Note imported messages might not appear as clean as you would hope, so you might
have to edit them by hand before commiting them to your repository.

.Generate messages/enums only
[source,shell]
----
./proto2asciidoc --source $(pwd)examples/examples.proto --out docs/generated/message_enums_only.adoc --overwrite
----